clear_output: true
force_cpu: false
live_cam_start_active: false
max_threads: 9
memory_limit: 0
output_image_format: png
output_template: '{file}_{time}'
output_video_codec: libx264
output_video_format: mp4
provider: cuda
selected_theme: Default
server_name: ''
server_port: 8080
server_share: true
video_quality: 14
